### ISSUE TITLE
Title and subtitle overlap

### ISSUE THREAD

**Issue by voltdatalab** [maxharlow/graphik#5]
This is a great tool, thank you for it! 

I don't know if this just happens to me, but my subtitle keeps overlapping with my subtitle for some reason. I can't find a solution for this. Is there a quick fix? 

![screen shot 2017-01-28 at 22 48 53](https://cloud.githubusercontent.com/assets/13594270/22401035/940efaec-e5ac-11e6-90cd-28c602b401ce.png)

**Comment by maxharlow** [comment]
Thanks -- glad you've found it useful!

What browser are you seeing that on?

**Comment by voltdatalab** [comment]
I am using Chrome. Funny enough, when I use your version (http://maxharlow.com/graphik), it works fine online, but not in my own localhost nor when I deploy to my GH Pages. 

I just tested in Safari, and it works alright even online. Funny. Must be some plugin I have in Chrome, but your version works well. I haven't change a single line of code.

**Comment by maxharlow** [comment]
I've made [some changes](https://github.com/maxharlow/graphik/commit/fff1295ac379553101c33c0e23ee7c3effd17980). Could you check if that's fixed it for you?

**Comment by voltdatalab** [comment]
It worked. Tks, Max. 

Its a really great tool. Appreciate that.
